//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoDemo.WinPhone
{
    
    
    public sealed class BandLayout
    {
        
        /// <summary>
        /// Loads PageLayout for BandLayout.blml.
        /// </summary>
        public static Microsoft.Band.Tiles.Pages.PageLayout Load()
        {
            // Width and Height of the elements are decreased of a pixel to prevent a serialization bug of the SDK.
            //Once this bug will be solved you will only have to update this extension and save the layout again.
            // 
            // scrollFlowPanel0
            // 
            Microsoft.Band.Tiles.Pages.ScrollFlowPanel scrollFlowPanel0 = new Microsoft.Band.Tiles.Pages.ScrollFlowPanel();
            scrollFlowPanel0.Orientation = Microsoft.Band.Tiles.Pages.FlowPanelOrientation.Vertical;
            scrollFlowPanel0.Rect = new Microsoft.Band.Tiles.Pages.PageRect(0, 0, 244, 101);
            // 
            // wrappedTextBlock11
            // 
            Microsoft.Band.Tiles.Pages.WrappedTextBlock wrappedTextBlock11 = new Microsoft.Band.Tiles.Pages.WrappedTextBlock();
            wrappedTextBlock11.Font = Microsoft.Band.Tiles.Pages.WrappedTextBlockFont.Small;
            wrappedTextBlock11.ElementId = new System.Nullable<short>(11);
            wrappedTextBlock11.Margins = new Microsoft.Band.Tiles.Pages.Margins(15, 0, 15, 0);
            wrappedTextBlock11.Rect = new Microsoft.Band.Tiles.Pages.PageRect(0, 0, 244, 101);
            scrollFlowPanel0.Elements.Add(wrappedTextBlock11);
            Microsoft.Band.Tiles.Pages.PageLayout layout = new Microsoft.Band.Tiles.Pages.PageLayout();
            layout.Root = scrollFlowPanel0;
            return layout;
        }
    }
}
